# Generated by Django 3.2.5 on 2024-11-30 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_student_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='branch',
            field=models.CharField(choices=[('MAIN', 'Main Exam System')], default='COMP', max_length=5),
        ),
        migrations.AlterField(
            model_name='student',
            name='division',
            field=models.CharField(choices=[('A', 'A')], default='A', max_length=1),
        ),
        migrations.AlterField(
            model_name='student',
            name='standard',
            field=models.CharField(choices=[('EX', 'EX')], default='FE', max_length=2),
        ),
        migrations.AlterField(
            model_name='studentrequest',
            name='branch',
            field=models.CharField(choices=[('MAIN', 'Main Exam System')], default='COMP', max_length=5),
        ),
        migrations.AlterField(
            model_name='studentrequest',
            name='division',
            field=models.CharField(choices=[('A', 'A')], default='A', max_length=1),
        ),
        migrations.AlterField(
            model_name='studentrequest',
            name='standard',
            field=models.CharField(choices=[('EX', 'EX')], default='FE', max_length=2),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='branch',
            field=models.CharField(choices=[('MAIN', 'Main Exam System')], default='COMP', max_length=5),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='division',
            field=models.CharField(choices=[('A', 'A')], default='A', max_length=1),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='standard',
            field=models.CharField(choices=[('EX', 'EX')], default='FE', max_length=2),
        ),
        migrations.AlterField(
            model_name='teacherrequest',
            name='branch',
            field=models.CharField(choices=[('MAIN', 'Main Exam System')], default='COMP', max_length=5),
        ),
        migrations.AlterField(
            model_name='teacherrequest',
            name='division',
            field=models.CharField(choices=[('A', 'A')], default='A', max_length=1),
        ),
        migrations.AlterField(
            model_name='teacherrequest',
            name='standard',
            field=models.CharField(choices=[('EX', 'EX')], default='FE', max_length=2),
        ),
    ]
